apiVersion: v1
kind: Service
metadata:
  name: raus-api-service
spec:
  selector:
    app: raus-api-webserver

  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 80
    - name: https
      port: 443
      targetPort: 5000