apiVersion: apps/v1
kind: Deployment
metadata:
  name: raus-api-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raus-api-webserver
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: raus-api-webserver
    spec:
      containers:
      - name: raus-api-webserver
        image: caiocfer/raus
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          periodSeconds: 120
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /status
            port: 5000
          periodSeconds: 120
       