name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Adds enviroment variables
        run: |
          sed -i '/EXPOSE 8080/i ENV SQLALCHEMY_DATABASE_URL=${{ secrets.SQLALCHEMY_DATABASE_URL }} \n' Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: caiocfer
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: caiocfer/raus
          context: .
          platforms: |-
              linux/amd64
              linux/arm64
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=gha
          cache-to: type=gha
          secrets: |
            SQLALCHEMY_DATABASE_URL={{ secrets.SQLALCHEMY_DATABASE_URL }}
  deploy:
    name: Deploy to kubernetes
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Get Kubeconfig context
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v3.1
        with:
          manifests: |
            ./.github/raus-deploy.yaml  
